# Generated by Django 3.2.16 on 2023-01-19 22:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import workspaces.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Workspace name. Must be between 3 and 50 characters long.', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)], verbose_name='title')),
                ('color', models.CharField(blank=True, default='#FFFFFF', max_length=16, null=True, verbose_name='color')),
                ('is_draft', models.BooleanField(default=False, help_text='Whether or not the workspace is in the middle of being created', verbose_name='is draft')),
            ],
            options={
                'db_table': 'workspace',
            },
            bases=(workspaces.mixins.WorkspaceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkspaceOnboardingSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('CF', 'Configure settings')], max_length=2, null=True)),
                ('title', models.CharField(max_length=1000, verbose_name='title')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceOnboarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wo_through', to='workspaces.workspaceonboardingsteps')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
        ),
    ]
